// Auto-generated by risc0-build
// This includes the compiled ELF binary and Image ID for each guest program
include!(concat!(env!("OUT_DIR"), "/methods.rs"));

// Re-export for convenience
// After building, these will be available as:
// - AAVE_GUEST_ELF: The compiled RISC-V binary
// - AAVE_GUEST_ID: The unique Image ID (cryptographic hash of the program)
pub use AAVE_GUEST_ELF as AAVE_ELF;
pub use AAVE_GUEST_ID as AAVE_ID;
